sepkg/studiopkg updated 4.0/5.3

diff --git a/tools/sepkg/sepkg-4.0/usr/sbin/sepkg b/tools/sepkg/sepkg-4.0/usr/sbin/sepkg
--- a/tools/sepkg/sepkg-4.0/usr/sbin/sepkg
+++ b/tools/sepkg/sepkg-4.0/usr/sbin/sepkg
@@ -26,7 +26,7 @@
 init()
 {
     APPNAME="sepkg"
-    VERSION="3.9b1"
+    VERSION="4.0b1"
     CONFDIR=/etc/$APPNAME/
     mkdir -p $CONFDIR
     CONF=$CONFDIR/$APPNAME.conf
@@ -269,8 +269,24 @@ make_queue()
             if [ -n "$SUB" ]; then
                 if [ ! -r $CWD/$SUB.sqf ]; then
                     pkg=$(cat $FILELIST | cut -d'/' -f4 | grep -xi $SUB.tar.gz)
-                    CAT=$(grep -wi $SUB $FILELIST | cut -d/ -f2)
-                    wget $SBSERVER/$CAT/$SUB/$SUB.sqf
+                    CAT=$(grep -wi $SUB $FILELIST | cut -d/ -f2 | tail -n1)
+
+                    if [ ! -r $SUB.sqf ]; then
+
+                        if [ -n "$CAT" ]; then
+                            if [ "$CAT" = "$SUB" ]; then
+                                $WGET -O $SUB.sqf $SBSERVER/$SUB.sqf
+                            else
+                                $WGET -O $SUB.sqf $SBSERVER/$CAT/$SUB/$SUB.sqf
+                            fi
+                        else
+                            $WGET -O $SUB.sqf $SBSERVER/$SUB.sqf
+                        fi
+                        if [ $? != 0 ]; then
+                            echo "$SUB.sqf not found"
+                            cleanup
+                        fi
+                    fi
                 else
                     cat $CWD/$SUB.sqf > $SUB.sqf
                 fi
@@ -287,12 +303,13 @@ make_queue()
 
     done < $1
 }
-#}}
-#{{ List Packages
+#}}}
+#{{{ List Packages
 listpkgs()
 {
     exec <&1
     unset pkgs
+    unset INSTALLLIST
 
     echo "Building queue..."
 
@@ -308,6 +325,7 @@ listpkgs()
     done
     
     echo -n > $TMPQ
+
     while read line
     do
         if [ ! $(grep -x $line $TMPQ) ]; then
@@ -335,12 +353,46 @@ listpkgs()
     if [ -z "$INSTALLLIST" ]; then cleanup; fi
 
     dialog --separate-output --title install --backtitle "$APPNAME $VERSION" \
+        --help-button --help-label "Clear Inst'd" --help-status \
         --checklist "Choose packages to install:" \
         19 70 13 $INSTALLLIST 2>$PKGLIST
-    if [ $? -ne 0 ]; then cleanup; fi
+    
+    CHOICE=$?
+
+    if [ $CHOICE -eq 2 ] && $(sed -i 's%^HELP %%g' $PKGLIST); then
+        clear_installed
+        listpkgs
+    fi
+
+    if [ $CHOICE -ne 0 ]; then cleanup; fi
     if [ -z "$(cat $PKGLIST)" ]; then cleanup; fi
 
     installpkgs
+}
+#}}}
+#{{{ Clear Installed
+clear_installed()
+{
+    while read newpkg
+    do
+        for o in $(ls /var/log/packages/$newpkg* 2>/dev/null)
+        do
+            oldpkg=$(echo $o | cut -d/ -f5 | rev | cut -d- -f4- | rev)
+
+            if [ -n "$(echo $oldpkg | grep upgraded)" ]; then
+                oldpkg="NULL"
+            fi
+
+            if [ "$newpkg" == "$oldpkg" ]; then
+                sed -i "/$newpkg$/d" $QUEUE
+            fi
+        done
+    done < $QUEUE
+
+    if [ $(wc -l $QUEUE | awk '{print $1}') = "0" ]; then
+        echo "All packages are already installed."
+        cleanup
+    fi
 }
 #}}}
 #{{{ Install Packages
diff --git a/tools/studiopkg/studiopkg-5.3/usr/sbin/studiopkg b/tools/studiopkg/studiopkg-5.3/usr/sbin/studiopkg
--- a/tools/studiopkg/studiopkg-5.3/usr/sbin/studiopkg
+++ b/tools/studiopkg/studiopkg-5.3/usr/sbin/studiopkg
@@ -26,7 +26,7 @@
 init()
 {
     APPNAME="studiopkg"
-    VERSION="5.2b1"
+    VERSION="5.3b1"
     TMPROOT=$(mktemp -d -p /tmp $APPNAME-XXXXXX) || exit
     trap "cleanup" HUP INT ABRT QUIT SEGV TERM KILL PIPE STOP TSTP
     
@@ -56,7 +56,7 @@ init()
     MAINURL="http://www.studioware.org"
     TOOLURL="$MAINURL/files/tools/$APPNAME"
     PKGSERVER="$MAINURL/files/packages/slackware$ARCH-$SWVERSION"
-    SBSERVER="$MAINURL/files/slackbuilds/$SWVERSION"
+    SBSERVER="$MAINURL/files/slackbuilds/.subs"
     CACHEDIR=/var/cache/$APPNAME/$SWVERSION
     mkdir -p $CACHEDIR
     FILELIST=$CACHEDIR/FILELIST.TXT
@@ -220,8 +220,8 @@ localqueue()
     else
         echo $cl | sed 's/,/\n/g;/^$/d' > $QUEUE
     fi
-    exec <&1
 
+    exec <&1
     listpkgs
 }
 #}}}
@@ -236,7 +236,6 @@ get_queue()
     cd $TMPROOT || cleanup
 
     CAT=$(grep -i $1-[^-]*-[^-]*-[^-]*txz$ $FILELIST | cut -d/ -f2)
-
     curl -fs $SBSERVER/$CAT/$1/$1.sqf > $QUEUE 
 
     if [ $? != 0 ]; then
@@ -256,7 +255,8 @@ make_queue()
 {
     cd $TMPROOT
     let CNT=1
-
+    touch $TMPQ
+    
     while read line
     do
         TOP=$(head -n $((CNT-1)) $TMPQ)
@@ -274,7 +274,15 @@ make_queue()
                     CAT=$(grep -i $SUB-[^-]*-[^-]*-[^-]*txz$ $FILELIST | cut -d/ -f2)
 
                     if [ ! -r $SUB.sqf ]; then
-                        wget -O $SUB.sqf $SBSERVER/$CAT/$SUB/$SUB.sqf
+                        $WGET -O $SUB.sqf $SBSERVER/$CAT/$SUB/$SUB.sqf
+
+                        if [ $? != 0 ]; then
+                            $WGET -O $SUB.sqf $SBSERVER/$SUB.sqf
+                        fi
+                        if [ $? != 0 ]; then
+                            echo "$SUB.sqf not found"
+                            cleanup
+                        fi
                     fi
                 else
                     cat $CWD/$SUB.sqf > $SUB.sqf
@@ -327,8 +335,8 @@ listpkgs()
     while read line
     do
         name=$(echo $line | awk '{print $1}')
-        
         pkg=$(grep -i /$name-[^-]*-[^-]*-[^-]*txz$ $FILELIST | cut -d/ -f3)
+        
         if [ -n "$pkg" ]; then
             INSTALLLIST=$INSTALLLIST" "$pkg" "$name" ""on "
         else
@@ -355,6 +363,7 @@ listpkgs()
         clear_installed
         listpkgs
     fi
+
     if [ $CHOICE -ne 0 ]; then cleanup; fi
     if [ -z "$(cat $PKGLIST)" ]; then cleanup; fi
 
@@ -801,3 +810,5 @@ deletecache()
 #}}}
 init
 getflags "$@"
+
+# vim: tw=0
